In [1]:
import os
import sys

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

from src.load_data import load_data

df = load_data()

print(df.shape)
df.head()

(1067371, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [2]:
df["TotalAmount"] = df["Quantity"] * df["Price"]

df[["Quantity", "Price", "TotalAmount"]].head()

   Quantity  Price  TotalAmount
0        12   6.95         83.4
1        12   6.75         81.0
2        12   6.75         81.0
3        48   2.10        100.8
4        24   1.25         30.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
 8   TotalAmount  1067371 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 73.3 MB

In [4]:
# Create date and time features
df["InvoiceYear"] = df["InvoiceDate"].dt.year
df["InvoiceMonth"] = df["InvoiceDate"].dt.month
df["InvoiceDay"] = df["InvoiceDate"].dt.day
df["DayOfWeek"] = df["InvoiceDate"].dt.day_name()
df["InvoiceHour"] = df["InvoiceDate"].dt.hour

# Display the new columns
df[[
    "InvoiceDate",
    "InvoiceYear",
    "InvoiceMonth",
    "InvoiceDay",
    "DayOfWeek",
    "InvoiceHour"
]].head(10)

,InvoiceDate,InvoiceYear,InvoiceMonth,InvoiceDay,DayOfWeek,InvoiceHour
0,2009-12-01 07:45:00,2009,12,1,Tuesday,7
1,2009-12-01 07:45:00,2009,12,1,Tuesday,7
2,2009-12-01 07:45:00,2009,12,1,Tuesday,7
3,2009-12-01 07:45:00,2009,12,1,Tuesday,7
4,2009-12-01 07:45:00,2009,12,1,Tuesday,7
5,2009-12-01 07:45:00,2009,12,1,Tuesday,7
6,2009-12-01 07:45:00,2009,12,1,Tuesday,7
7,2009-12-01 07:45:00,2009,12,1,Tuesday,7
8,2009-12-01 07:46:00,2009,12,1,Tuesday,7
9,2009-12-01 07:46:00,2009,12,1,Tuesday,7

In [5]:
import pandas as pd

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 14 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Invoice       1067371 non-null  str
 1   StockCode     1067371 non-null  str
 2   Description   1062989 non-null  str
 3   Quantity      1067371 non-null  int64
 4   InvoiceDate   1067371 non-null  datetime64[us]
 5   Price         1067371 non-null  float64
 6   Customer ID   824364 non-null   float64
 7   Country       1067371 non-null  str
 8   TotalAmount   1067371 non-null  float64
 9   InvoiceYear   1067371 non-null  int32
 10  InvoiceMonth  1067371 non-null  int32
 11  InvoiceDay    1067371 non-null  int32
 12  DayOfWeek     1067371 non-null  str
 13  InvoiceHour   1067371 non-null  int32
dtypes: datetime64[us](1), float64(3), int32(4), int64(1), str(5)
memory usage: 97.7 MB

In [6]:
# Create date and time features
df["InvoiceYear"] = df["InvoiceDate"].dt.year
df["InvoiceMonth"] = df["InvoiceDate"].dt.month
df["InvoiceDay"] = df["InvoiceDate"].dt.day
df["DayOfWeek"] = df["InvoiceDate"].dt.day_name()
df["InvoiceHour"] = df["InvoiceDate"].dt.hour

# Display the new columns
df[[
    "InvoiceDate",
    "InvoiceYear",
    "InvoiceMonth",
    "InvoiceDay",
    "DayOfWeek",
    "InvoiceHour"
]].head(10)

,InvoiceDate,InvoiceYear,InvoiceMonth,InvoiceDay,DayOfWeek,InvoiceHour
0,2009-12-01 07:45:00,2009,12,1,Tuesday,7
1,2009-12-01 07:45:00,2009,12,1,Tuesday,7
2,2009-12-01 07:45:00,2009,12,1,Tuesday,7
3,2009-12-01 07:45:00,2009,12,1,Tuesday,7
4,2009-12-01 07:45:00,2009,12,1,Tuesday,7
5,2009-12-01 07:45:00,2009,12,1,Tuesday,7
6,2009-12-01 07:45:00,2009,12,1,Tuesday,7
7,2009-12-01 07:45:00,2009,12,1,Tuesday,7
8,2009-12-01 07:46:00,2009,12,1,Tuesday,7
9,2009-12-01 07:46:00,2009,12,1,Tuesday,7

In [7]:
# Customer-level feature engineering

customer_features = (
    df.groupby("Customer ID")
      .agg(
          TotalSpend=("TotalAmount", "sum"),
          TotalOrders=("Invoice", "nunique"),
          TotalProducts=("Quantity", "sum"),
          AverageOrderValue=("TotalAmount", "mean")
      )
      .reset_index()
)

customer_features.head()

   Customer ID  TotalSpend  TotalOrders  TotalProducts  AverageOrderValue
0      12346.0      -64.68           17             52          -1.347500
1      12347.0     5633.32            8           3286          22.266087
2      12348.0     2019.40            5           2714          39.596078
3      12349.0     4404.54            5           1619          24.469667
4      12350.0      334.40            1            197          19.670588

In [15]:
# First purchase date for each customer
first_purchase = (
    df.groupby("Customer ID")["InvoiceDate"]
      .min()
      .reset_index()
      .rename(columns={"InvoiceDate": "FirstPurchase"})
)

# Last purchase date for each customer
last_purchase = (
    df.groupby("Customer ID")["InvoiceDate"]
      .max()
      .reset_index()
      .rename(columns={"InvoiceDate": "LastPurchase"})
)

# Merge with customer features
customer_features = customer_features.merge(first_purchase, on="Customer ID")
customer_features = customer_features.merge(last_purchase, on="Customer ID")

# Calculate customer tenure (days)
customer_features["CustomerTenure"] = (
    customer_features["LastPurchase"] -
    customer_features["FirstPurchase"]
).dt.days

customer_features.head()

,Customer ID,TotalSpend,TotalOrders,TotalProducts,AverageOrderValue,FirstPurchase,LastPurchase,CustomerTenure
0,12346.0,-64.68,17,52,-1.347500,2009-12-14 08:34:00,2011-01-18 10:17:00,400
1,12347.0,5633.32,8,3286,22.266087,2010-10-31 14:20:00,2011-12-07 15:52:00,402
2,12348.0,2019.40,5,2714,39.596078,2010-09-27 14:59:00,2011-09-25 13:13:00,362
3,12349.0,4404.54,5,1619,24.469667,2009-12-04 12:49:00,2011-11-21 09:51:00,716
4,12350.0,334.40,1,197,19.670588,2011-02-02 16:01:00,2011-02-02 16:01:00,0

In [16]:
# Avoid division by zero for customers with 0-day tenure
customer_features["TenureMonths"] = (
    customer_features["CustomerTenure"] / 30
).replace(0, 1)

# Purchase Frequency per Month
customer_features["PurchaseFrequencyPerMonth"] = (
    customer_features["TotalOrders"] /
    customer_features["TenureMonths"]
)

customer_features.head()

,Customer ID,TotalSpend,TotalOrders,TotalProducts,AverageOrderValue,FirstPurchase,LastPurchase,CustomerTenure,TenureMonths,PurchaseFrequencyPerMonth
0,12346.0,-64.68,17,52,-1.347500,2009-12-14 08:34:00,2011-01-18 10:17:00,400,13.333333,1.275000
1,12347.0,5633.32,8,3286,22.266087,2010-10-31 14:20:00,2011-12-07 15:52:00,402,13.400000,0.597015
2,12348.0,2019.40,5,2714,39.596078,2010-09-27 14:59:00,2011-09-25 13:13:00,362,12.066667,0.414365
3,12349.0,4404.54,5,1619,24.469667,2009-12-04 12:49:00,2011-11-21 09:51:00,716,23.866667,0.209497
4,12350.0,334.40,1,197,19.670588,2011-02-02 16:01:00,2011-02-02 16:01:00,0,1.000000,1.000000

In [17]:
# Average Spend per Product
customer_features["AverageSpendPerProduct"] = (
    customer_features["TotalSpend"] /
    customer_features["TotalProducts"]
)

customer_features.head()

,Customer ID,TotalSpend,TotalOrders,TotalProducts,AverageOrderValue,FirstPurchase,LastPurchase,CustomerTenure,TenureMonths,PurchaseFrequencyPerMonth,AverageSpendPerProduct
0,12346.0,-64.68,17,52,-1.347500,2009-12-14 08:34:00,2011-01-18 10:17:00,400,13.333333,1.275000,-1.243846
1,12347.0,5633.32,8,3286,22.266087,2010-10-31 14:20:00,2011-12-07 15:52:00,402,13.400000,0.597015,1.714340
2,12348.0,2019.40,5,2714,39.596078,2010-09-27 14:59:00,2011-09-25 13:13:00,362,12.066667,0.414365,0.744068
3,12349.0,4404.54,5,1619,24.469667,2009-12-04 12:49:00,2011-11-21 09:51:00,716,23.866667,0.209497,2.720531
4,12350.0,334.40,1,197,19.670588,2011-02-02 16:01:00,2011-02-02 16:01:00,0,1.000000,1.000000,1.697462

In [18]:
# Average Quantity per Order
customer_features["AverageQuantityPerOrder"] = (
    customer_features["TotalProducts"] /
    customer_features["TotalOrders"]
)

customer_features.head()

,Customer ID,TotalSpend,TotalOrders,TotalProducts,AverageOrderValue,FirstPurchase,LastPurchase,CustomerTenure,TenureMonths,PurchaseFrequencyPerMonth,AverageSpendPerProduct,AverageQuantityPerOrder
0,12346.0,-64.68,17,52,-1.347500,2009-12-14 08:34:00,2011-01-18 10:17:00,400,13.333333,1.275000,-1.243846,3.058824
1,12347.0,5633.32,8,3286,22.266087,2010-10-31 14:20:00,2011-12-07 15:52:00,402,13.400000,0.597015,1.714340,410.750000
2,12348.0,2019.40,5,2714,39.596078,2010-09-27 14:59:00,2011-09-25 13:13:00,362,12.066667,0.414365,0.744068,542.800000
3,12349.0,4404.54,5,1619,24.469667,2009-12-04 12:49:00,2011-11-21 09:51:00,716,23.866667,0.209497,2.720531,323.800000
4,12350.0,334.40,1,197,19.670588,2011-02-02 16:01:00,2011-02-02 16:01:00,0,1.000000,1.000000,1.697462,197.000000

In [8]:
# Latest date in the dataset
snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

# RFM features
rfm = (
    df.groupby("Customer ID")
      .agg({
          "InvoiceDate": lambda x: (snapshot_date - x.max()).days,
          "Invoice": "nunique",
          "TotalAmount": "sum"
      })
      .reset_index()
)

# Rename columns
rfm.columns = ["Customer ID", "Recency", "Frequency", "Monetary"]

rfm.head()

   Customer ID  Recency  Frequency  Monetary
0      12346.0      326         17    -64.68
1      12347.0        2          8   5633.32
2      12348.0       75          5   2019.40
3      12349.0       19          5   4404.54
4      12350.0      310          1    334.40

In [9]:
# Latest date in the dataset
snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

# RFM features
rfm = (
    df.groupby("Customer ID")
      .agg({
          "InvoiceDate": lambda x: (snapshot_date - x.max()).days,
          "Invoice": "nunique",
          "TotalAmount": "sum"
      })
      .reset_index()
)

# Rename columns
rfm.columns = ["Customer ID", "Recency", "Frequency", "Monetary"]

rfm.head()

   Customer ID  Recency  Frequency  Monetary
0      12346.0      326         17    -64.68
1      12347.0        2          8   5633.32
2      12348.0       75          5   2019.40
3      12349.0       19          5   4404.54
4      12350.0      310          1    334.40

In [10]:
# Merge customer features with RFM features

customer_dataset = customer_features.merge(
    rfm,
    on="Customer ID",
    how="left"
)

customer_dataset.head()

,Customer ID,TotalSpend,TotalOrders,TotalProducts,AverageOrderValue,Recency,Frequency,Monetary
0,12346.0,-64.68,17,52,-1.347500,326,17,-64.68
1,12347.0,5633.32,8,3286,22.266087,2,8,5633.32
2,12348.0,2019.40,5,2714,39.596078,75,5,2019.40
3,12349.0,4404.54,5,1619,24.469667,19,5,4404.54
4,12350.0,334.40,1,197,19.670588,310,1,334.40

In [11]:
# Remove duplicate column
customer_dataset = customer_dataset.drop(columns=["TotalSpend"])

customer_dataset.head()

,Customer ID,TotalOrders,TotalProducts,AverageOrderValue,Recency,Frequency,Monetary
0,12346.0,17,52,-1.347500,326,17,-64.68
1,12347.0,8,3286,22.266087,2,8,5633.32
2,12348.0,5,2714,39.596078,75,5,2019.40
3,12349.0,5,1619,24.469667,19,5,4404.54
4,12350.0,1,197,19.670588,310,1,334.40

In [12]:
# Save feature engineered dataset

output_path = "../data/processed/customer_features.csv"

customer_dataset.to_csv(output_path, index=False)

print("Feature engineered dataset saved successfully!")

Feature engineered dataset saved successfully!

In [13]:
import os

print(os.path.exists(output_path))

True

In [14]:
print("Hello")

Hello

In [19]:
# Save updated customer features
customer_features.to_csv(
    "../data/processed/customer_features.csv",
    index=False
)

print("Updated customer_features.csv saved successfully!")

Updated customer_features.csv saved successfully!